services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    Creode\AvatarBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Creode\AvatarBundle\Workflow\:
        resource: '../../Workflow'
        public: true

    Creode\AvatarBundle\Tools\Installer:
        public: true

    creode.avatar.event_listener:
        class: Creode\AvatarBundle\EventListener\AvatarEventListener
        tags:
            - {
                name: kernel.event_listener,
                event: pimcore.dataobject.guardPublish,
                method: guardPublish
            }

# add more services, or override services that need manual wiring
#    Creode\AvatarBundle\ExampleClass:
#        arguments:
#            - "@service_id"
#            - "plain_value"
#            - "%parameter%"
